# Generated by Django 5.1.3 on 2024-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BFCONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
    ]
